### ISSUE TITLE
View the companion reference site is not working

### ISSUE THREAD

**Issue by itsthomas** [nsmsn/github-for-web-designers#1]
Hi James,

I've just started your course on Lynda.com.
Unfortunately the "View the companion reference site" link of your Repo shows a 404 error.

**Comment by nsmsn** [comment]
Hi itsthomas,

Here's the original repo for the Lynda.com course: https://github.com/jameswillweb/github-for-web-designers

My exercise for this may have disappeared after I started publishing my personal site with GitHub Pages
